spring.application.name=crime-job
#
spring.batch.jdbc.initialize-schema=always
spring.sql.init.mode=always
bootiful.batch.chunk.leader=true
#
spring.datasource.password=secret
spring.datasource.username=myuser
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
#
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret