spring.application.name=report-producer
bootiful.batch.chunk.worker=true
#
spring.datasource.password=secret
spring.datasource.username=myuser
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
#
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret


