spring.application.name=crime-job
#
spring.batch.jdbc.initialize-schema=always
spring.sql.init.mode=always
#
spring.datasource.password=secret
spring.datasource.username=myuser
spring.datasource.url=jdbc:postgresql://localhost/mydatabase